# Generated by Django 4.1.3 on 2024-02-29 05:41

import app.models
import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.CharField(default="", max_length=10, primary_key=True, serialize=False, unique=True)),
                ('video', models.FileField(upload_to='')),
                ('thumbnail', models.FileField(upload_to='')),
                ('title', models.CharField(max_length=32)),
                ('description', models.CharField(max_length=128)),
                ('date', models.DateField(default=datetime.date.today)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='videos', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
