# Generated by Django 4.1.3 on 2024-02-29 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='thumbnail',
            field=models.FileField(default=None, upload_to=''),
        ),
    ]
