# Generated by Django 4.1.3 on 2024-03-01 02:56

import app.models
import cloudinary.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_alter_video_video'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='video',
            field=cloudinary.models.CloudinaryField(max_length=255, verbose_name=models.CharField(default=app.models.generate_unique_id, max_length=10, primary_key=True, serialize=False, unique=True)),
        ),
    ]
