# Generated by Django 4.1.3 on 2024-03-01 06:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_alter_video_video'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='video',
            name='thumbnail',
        ),
    ]
