# Generated by Django 4.1.3 on 2024-03-02 18:35

import cloudinary.models
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_remove_video_thumbnail'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='video',
            name='video',
        ),
        migrations.AddField(
            model_name='video',
            name='file',
            field=cloudinary.models.CloudinaryField(default=None, max_length=255, verbose_name=models.CharField(default=uuid.uuid1, max_length=10, primary_key=True, serialize=False, unique=True)),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='video',
            name='description',
            field=models.CharField(blank=True, max_length=128),
        ),
        migrations.AlterField(
            model_name='video',
            name='id',
            field=models.CharField(default=uuid.uuid1, max_length=10, primary_key=True, serialize=False, unique=True),
        ),
    ]
