# Generated by Django 4.1.3 on 2024-03-03 03:23

import cloudinary.models
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_remove_video_video_video_file_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='file',
            field=cloudinary.models.CloudinaryField(max_length=255, verbose_name=models.CharField(default=uuid.uuid1, max_length=36, primary_key=True, serialize=False, unique=True)),
        ),
        migrations.AlterField(
            model_name='video',
            name='id',
            field=models.CharField(default=uuid.uuid1, max_length=36, primary_key=True, serialize=False, unique=True),
        ),
    ]
